- src/main.ts
just console logging the area measurements for now until we make more design decisions! open layers ["measure" examples](https://openlayers.org/en/latest/examples/measure.html) use dynamic tooltips directly on the map, while planx currently renders total area outside of map container.
> feat: calculate area of polygons

- index.html
- src/my-map.ts
custom control button to reset to original zoom & center and clear any drawn features if they exist.
also disabling rotation which should fix #6. 
maybe this should be dispatching an event like #13 though?
> feat: reset control to clear drawing

- src/draw.ts
- src/my-map.ts
- src/os-layers.ts
- Red dashed line while drawing in-progress, solid red when closed or modifying (we'll save "blue lines" for feature selection this way, which seems consistent with how people have been talking about address outlines)
- Simple cursor distinction for moving versus panning/dragging (click+hold). At one point there was an "accessibility" card that asked for the cursor to be a 'pencil' if in draw mode, but I think that's a bit harder & lower prio - so keeping the red circle for now which I'd also argue is maybe still best for clearing showing where your points will be placed
- Prettier formatting
> chore: draw styles cleanup

- src/draw.ts
- src/my-map.ts
- src/utils.ts
quick clean up that'll make it easier to share formatArea function between drawings and other polygons (rendered geojson or selected features)
adding optional units param for hectares while it's fresh, but won't close that related Trello card as it's framed as ability to toggle between units in the UI
> chore: formatArea as shared util, optionally calculate in hectares

- README.md
- src/draw.ts
- src/my-map.ts
- adds an outlineLayer that is by default empty, but can read & display features from a geojson data object if provided
- optional `geojsonColor` param to specify a custom hex code for the outline (defaults to red)
- if geojson is provided, re-fit the map view based on the extent of the features overriding default zoom & center. reset control will reference the same extent. optional `geojsonBuffer` param to control how much the extent should be buffered
- calculates & logs the total area of the geojson feature if provided
open questions:
- currently allowing drawMode true & static polygon to co-exist because I think this will satisfy BOP's use case of displaying the current site plan & then drawing an amendment on the same map - does that sound right?
- you can currently add any type of …
> feat: display a static polygon if geojson provided

- README.md
- src/my-map.ts
- src/os-features.ts
creeping into the "future" features with this one, but the logic was basically already on hand from our first implementation! this will let us show a border around the address point in FindProperty component & move towards having a more accurate polygon/geojson to make more accurate planning constraint queries in the future.
example implementation:
```html
<my-map latitude="51.4858363" longitude="-0.0761246" showFeaturesAtPoint featureColor="#8a2be2" />
```
> feat: query & display features that intersect with lon,lat

- package.json
- pnpm-lock.yaml
- src/my-map.ts
I think lit-element is deprecated now and lit is a monorepo that we should be tracking?
> upgrade from lit-element > lit

- README.md
this was the last key feature missing from existing README examples. Definitely interested in researching more formal ways to document web components in the future, but README is feeling easy for now as things are changing often.
> docs: add drawMode example to README

- README.md
- src/my-map.ts
> fix: account for FeatureCollection and Feature geojson types

- README.md
- src/my-map.ts
Closes #32 
Two initial use cases:
- BOPs only wants to show the "reset" button when drawMode is enabled. If they're loading geojson they can hide it
- PlanX wants to hide _all_ controls and disable zoom/pan interactions in our Review component
> feat: hideResetControl and staticMode props

- src/my-map.ts
Fixes #38 
Was introduced when I adjusted geojsonData to accept type "Feature" _or_ "FeatureCollection", so was only erasing "FeatureCollection" geojson formats and still ignoring newly supported type "Feature" - works for both now!
> fix: 'reset' erases drawing when geojson data is also displayed

- index.html
- src/draw.ts
- Show vertices of drawn polygon once a shape has been closed; user can modify existing vertices or add new ones (design similar to MapInfo Professional used internally at Buckinghamshire)
- Tweak default drawing style to have more prominent fill color
- Increase snap pixel tolerance against drawing layer so it's a bit easier to close your drawing & grab an existing vertex to modify
> feat: show vertices of drawn polygon

- src/my-map.ts
- src/scale-line.ts
Add scale bar to maps
https://trello.com/c/3LkxI6Kd/448-map-scale-bar-required-on-decision-notice
Co-authored-by: Rhian Lewis <rhianatwork@gmail.com>
> Add scale bar to map

- src/my-map.ts
- src/utils.ts
Closes #63 
When `geojsonFill` is true/present, it assumes your fill color is your stroke color with 20% opacity. This is pretty consistent with drawing style defaults! It's false by default, so geojson data will still display with only a border color by default.
Example: 
```html
<my-map geojsonColor="#286e8a" geojsonFill />
<script>
const map = document.querySelector("my-map");
map.geojsonData = {
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {},
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
-0.11562466621398924,
51.50746034612789
],
[
-0.11449813842773436,
51.50617151942102
],
[
-0.11359691619873047,
51.50653212745768
],
[
-0.11348962783813477,
51.50645199258505
],
[
-0.1127493381500244,
51.50665900738443
],
[
-0.11383295059204103, …
```
> feat: add property to show fill color for geojson

- src/my-map.ts
- src/os-features.ts
Same idea as #64, my oversight to not group them into a single PR the first time!
> feat: add property to show fill color for features

- CHANGELOG.md
- index.html
- package.json
- src/drawing.ts
- src/my-map.ts
- src/os-features.ts
- src/snapping.ts
- src/utils.ts
looks like more than it is because i'm based off main!
makes sure we only add the snapping layer when in drawMode with the vectorTile basemap enabled
shuffles the code around a bit to keep it closer to drawing logic in the flow of my-map.ts, and moves a couple more definitions to snapping.ts
not thinking about styling yet! maybe just easiest to set a snapping color property so it's easy to keep changing minds about? :upside_down_face: 
also still thinking about how snaps should work once you close your shape? can we actually modify-to-snaps? if we cant, maybe points should disappear?
> tidy up snaps

- index.html
- src/draw.ts
- src/drawing.ts
- src/my-map.ts
- src/snapping.ts
- tsconfig.json
Implementation assumptions: 
- Snapping is only possible if OS Vector Tiles basemap is enabled (not OS Raster basemap or OSM); this requires OS API key
- Snapping points appear when `drawMode` is enabled and zoom level > 20
- Snapping points remain visible after you've closed your shape as reference points, but when modifying you won't get the same pixelTolerance/gravitational pull towards the snaps as you do when in initial drawing mode
Default styles:
- Drawing cursor is updated to red crosshair rather than dot
- Snapping points are solid black with a radius of 3 pixels, a bit smaller than drawing cursor and red drawing vertices
- Drawing vertices will always appear _on top of_ snapping points
- Color & size are currently not user configurable, but please say so if this is a MVP …
> feat: snap to vector tile basemap features

- src/my-map.ts
I think this should fix this issue with modify shape not snapping, apologies for the extra prettier noise! We'll get prettier running on everything in this repo again at some point.
Steps taken
- ensure snap interaction behaviour added _after_ draw and modify behaviours
- don't remove snap behaviour after completing shape
> fix: keep snapping behaviour while modifying polygon

- index.html
- src/drawing.ts
- src/my-map.ts
- src/snapping.ts
- `drawPointer` property accepts "crosshair" (default, so this isn't a breaking change) or "dot"
- grey snap points instead of black
> feat: configurable drawing pointer style

- src/my-map.ts
Accessibility report says that aria-label attributes are not allowed on divs and may cause random results for assistive technology. It recommendeds removing them entirely.
> break: remove ariaLabel property

- src/my-map.ts
- src/os-layers.ts
default copyright is updated to reflect our new agreement with DHLUC
`osCopyright` property now allows other users to overwrite based on their own API keys
(Netlify deploy env vars are similarly updated to reflect our new keys)
> feat: configurable copyright for OS data

- src/my-map.ts
Addresses issues raised in the following two tickets - 
- https://trello.com/c/NqjvZifP/1666-non-descriptive-links-and-buttons
- https://trello.com/c/luSUt9gd/1680-button-target-size
**Fixes**
- Ensure zoom and reset buttons are 44px x 44px
- Apply missing `pointer: cursor` to buttons
- Presumably the way that the drag and move pointers are set are causing this issue
- Apply `aria-label` attribute to controls
> fix: A11y improvements

- src/my-map.ts
fixes #96 
:crossed_fingers: this might/should fix planx bugs described here https://github.com/theopensystemslab/planx-new/pull/704
https://lit.dev/docs/components/lifecycle/#content
> fix: add disconnectedCallback() lifecycle method to unmount map

- index.html
- src/my-map.ts
- src/os-features.ts
**working solution:**
- add an `id` property so we can set a custom id on `<my-map />` element, defaults to "map" as before
- clear the featureSource upfront when only `showFeaturesAtPoint` is enabled, which should prevent prior query results from persisting in the layer. if `showFeaturesAtPoint` && `clickFeatures` are enabled (don't know of any prod uses of this yet), then we don't clear the source as before to allow for selecting/deselecting features on click
- clear the drawingSource upfront for _both_ cases: when we want to start drawing fresh AND when we want to load a previously drawn polygon into the drawingSource to modify. previously, we only cleared it in the case of starting a fresh drawing
**dugging notes:**
update `index.html` to something like this:
```html
<body>
<div …
```
> fix: add prop to set unique id on element & clear the featureSource unless `clickFeatures` is enabled

- pnpm-lock.yaml
I just ran `pnpm i` so that the pnpm-lock.yaml is up to date with the deps specified in package.json
not sure what happened with the commit name and description but if it's a squash and merge I suppose they don't matter
> `pnpm i` to bring lockfile up to date with package.json

- src/components/address-autocomplete/index.ts
- src/components/postcode-search/index.ts
am experiencing some unexpected screenreader behavior during [planx integration](https://github.com/theopensystemslab/planx-new/pull/887), hoping `tabindex="0"` will smooth it out! we were already setting `tabindex` on the main map div and that component is read out as expected by my screenreader, so I'm fairly hopeful here. 
this [2014(!) blog](https://marcysutton.com/accessibility-and-the-shadow-dom) reassures that elements rendered in the shadow DOM (as these web components are when integrated into our React frontend) should simply be part of "one happy tree" as far as screenreaders are concerned :deciduous_tree:
a few other minor fixes here too:
- clarify types & code comments
- better error handling
> fix: postcode-search & address-autocomplete should set tabindex="0"

- index.html
- src/components/address-autocomplete/index.ts
- src/components/address-autocomplete/styles.scss
This PR allows certain properties of the `address-autocomplete` component to be styled from a parent. The properties that have been given variables should marry up with any that we need to match the PlanX style.
Lit Docs - https://lit.dev/docs/components/styles/#theming
**Example with Lambeth primary colour**
**To Do**
> feat: Allow autocomplete to be styled from parent

- src/components/address-autocomplete/index.ts
the input is automatically rendered with a tabindex, so adding one on the container div was actually a mistake that will require two-tabs to be able to focus & start typing!
> fix: autocomplete container shouldn't have tabindex if input does

- index.html
- src/components/address-autocomplete/index.ts
- src/components/address-autocomplete/styles.scss
A few little fixes and improvements.
- Down arrow is visible on white background, and is now clickable (only to open, as original component works)
- Relates to this issue https://github.com/alphagov/accessible-autocomplete/issues/351
- New "light" down arrow option which is a little nicer looking 💅 
- Style doesn't break when focus and hover interact (see below)
- There's still a `:focus-visible` ring, see issue here - https://github.com/alphagov/accessible-autocomplete/issues/73
> feat: Improve style of autocomplete

- index.html
- src/components/address-autocomplete/index.ts
- src/components/address-autocomplete/styles.scss
Realised during Friday's show and tell that the label font size is 19px on PlanX when it should be 18px!
By default, the `govuk-label` class takes into account the following breakpoints - https://github.com/alphagov/govuk-frontend/blob/v4.0.0/src/govuk/settings/_media-queries.scss#L10-L14
This means it's not quite as simple as overwriting the font-size and setting a default, as this would have the side effect of breaking the responsiveness if anybody else wanted to use the component.
> feat: Enable static or responsive label on autocomplete

- src/components/address-autocomplete/index.ts
See following message (28/03/22) - 
> “We have noticed that the label for the autocomplete is not marked up correctly and comes across as unlabelled, this is due to the htmlfor and should just be ‘for’
> 
> `<label class="govuk-label" htmlfor="address-autocomplete">Select an address</label>`
>
> `<label class="govuk-label" for="address-autocomplete">Select an address</label>`
>
> As for functionality for the autocomplete this is much better but there is a slight issue where the status has been applied to an outside div which is resulting in the options all reading out in one go. This needs to be removed.
>
> `#address-autocomplete-container`
>
>`<div role="status" spellcheck="false" id="address-autocomplete-container"><div class="autocomplete__wrapper">`
>
>Please let me know when these …
> fix: Further a11y fixes for autocomplete

- index.html
- pnpm-lock.yaml
- src/components/address-autocomplete/index.ts
- src/components/postcode-search/index.ts
- src/components/postcode-search/styles.scss
- Adjust error message according to new `govuk-frontend` release [change note](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#update-the-html-for-error-messages)
- Dispatch an event on input change, rather than only when the postcode is validated - otherwise an integration in planx doesn't know when to (re)hide the address-autocomplete when a valid postcode is changed
- Added basic set of custom style properties ([Lit docs](https://lit.dev/docs/v1/components/styles/#configurable)) we'd likely want to configure/override in planx, following autocomplete example, but nothing too fancy or complex
- Use `for` not `htmlFor` to link label & input
> fix: postcode-search improvements

- src/components/my-map/index.ts
- src/components/my-map/os-features.ts
two styling features to help clarify how we highlight addresses: 
- boolean property `featureBorderNone` to control whether or not to show a border when highlighting an OS Feature that intersects with a point
```<my-map zoom="20" showFeaturesAtPoint featureFill="#fff" featureBorderNone />```
- boolean property `showMarker` to show a marker on the map (defaults to center latitude & longitude), with optional number properties `markerLatitude`, `markerLongitude` to specify a custom latitude & longitude to place the marker at. The marker will default to a black dot, but you can pass a custom hex code or CSS color name to `markerColor`.
```<my-map zoom="20" showMarker />```
> feat: show features without border & ability to add a custom marker

- src/components/address-autocomplete/main.test.ts
- src/components/my-map/main.test.ts
- src/components/postcode-search/main.test.ts
- vite.config.ts
recent dependency upgrades seem to have cleared up the previous openlayers type error that was effecting map unit tests :tada: 
additionally updated all unit tests to use `toBeTruthy` rather than `toBeDefined` as that would still pass for null elements
> feat: add basic unit tests for map component

- .github/workflows/pnpm-test.yml
- package.json
- pnpm-lock.yaml
- src/components/my-map/index.ts
- src/components/my-map/main.test.ts
- src/components/my-map/snapping.ts
Addresses https://trello.com/c/NZrvqg7d/2055-get-snap-points-on-map-to-always-load
Currently, points are automatically generated on the assumption that vector tiles will be loaded. On slower connections, this means that snap points either do not display or do not fully display. This can be mocked in the browser by throttling your connection speed.
This PR fixes this by waiting for the map `loadend` event before triggering the generation of the snap points. Originally I was listening for the vector source's `tileloadend` event but this fires for each tile load and then regenerates snap points which I imagine is both computationally expensive and could lead to inconsistent results (e.g. all snap points loading in one tile at a time).
Also - some basic OL tests! Couldn't quite get around a …
> fix: Ensure snap points always load

- src/components/my-map/controls.ts
- src/components/my-map/icons/README.md
- src/components/my-map/icons/erase.svg
- src/components/my-map/icons/reset.svg
- src/components/my-map/icons/trash-can.svg
- src/components/my-map/index.ts
- src/components/my-map/styles.scss
adds `resetControlImage` ENUM property to specify a custom icon to show on the reset control button. Defaults to our current unicode arrow.
This is a bit of a tricky UAT request because we need to make a whole release. Once an icon is decided on, an ENUM property will likely be unnecessary and we can clean this up. If we decide to go with one of these new options, it may also be worth considering to source all icons from Carbon rather than mixing libraries? 
| `resetControlImage` value  | display   |
|---|---|
| `unicode` (default) | ![Screenshot from 2022-10-14 10-11-37](https://user-images.githubusercontent.com/5132349/195797797-28599348-4f22-41d5-92d1-463e2d5ec865.png) |
| `reset`  |  ![Screenshot from 2022-10-14 10-09-53](https://user-images.githubusercontent.com/5132349/195797937-4ee6 …
> feat: add `resetControlImage` prop for testing custom icons

- index.html
- src/components/my-map/styles.scss
Override the default openlayers translucent blue with a cleaner style that better fits our Gov UK-esque styles
> chore: cleanup styling of default scale line

- src/components/my-map/drawing.ts
- src/components/my-map/index.ts
Context:
- `drawMode` previously assumed the geometry type "Polygon" because we've only used it for drawing site boundaries
- now, we want to support an additional drawing mode where you can plot a single point on the map to denote a "new address"
- i think it's safe to assume that we don't need to support drawing a polygon and point _at the same time on a single map_, so these functionalities can share a source
Changes:
- adds optional prop `drawType` to specify "Polygon" (default) or "Point" when using `drawMode`
- adds optional prop `drawPointColor` to specify the color of the feature
- only displays snap points when drawing a "Polygon"
- only dispatches the `areaChange` event when drawing a "Polygon"
- otherwise "Point" drawing carries the same assumptions as "Polygon": limit to 1 …
> feat: enable drawing single point

- tsconfig.json
A warning is being thrown in the dev sandbox console, pointing to the following docs -  https://lit.dev/docs/components/properties/\#avoiding-issues-with-class-fields
Possibly something picked up after the most recent updates?
> fix: Resolve shadow class fields warning

- docs/how-to-use-a-proxy.md
- index.html
- src/components/address-autocomplete/address-autocomplete.doc.js
- src/components/address-autocomplete/index.ts
- src/components/address-autocomplete/main.test.ts
- src/components/my-map/docs/my-map-basic.doc.js
- src/components/my-map/docs/my-map-draw.doc.js
- src/components/my-map/docs/my-map-features.doc.js
- src/components/my-map/docs/my-map-geojson.doc.js
- src/components/my-map/docs/my-map-proxy.doc.js
- src/components/my-map/index.ts
- src/components/my-map/main.test.ts
- src/components/my-map/os-features.ts
- src/components/my-map/os-layers.test.ts
- src/components/my-map/os-layers.ts
- src/lib/ordnanceSurvey.test.ts
- src/lib/ordnanceSurvey.ts
- src/test-utils.ts
- Support the use of a proxy via the `osProxyEndpoint` property
- This means that we do not need to expose the OS API key when making requests
Before making any requests to the OS, we get the URL from `ordnanceSurvey.getServiceURL()`. 
If the user supplied an OS API key, we'll query the OS API directly and append their key. This is the exact same functionality as currently exists.
If the user supplies an `osProxyEndpoint` value, we'll construct the correct service URL, without an API key. It is the end user's responsibility to host and maintain a suitable service to proxy requests (with the correct authentication) to the OS API.  Ensuring proper access to the proxy endpoint can be done through CORS/CORP on the proxy. The documentation in this repository outlines how this can be achieved. …
> feat: Hide OS API key by allowing proxy endpoint

- src/components/my-map/docs/my-map-draw.doc.js
Should have spotted this one alongside https://github.com/theopensystemslab/map/pull/238 sorry!
> fix: Fix drawGeojsonData example in docs

- src/components/my-map/controls.ts
- src/components/my-map/index.ts
- src/components/my-map/styles.scss
Fixes https://github.com/theopensystemslab/map/issues/227
Picked this up whilst looking at https://trello.com/c/jVS79IdF/2230-can-automatically-generated-location-plan-click-to-standard-scales
> fix: Display scalebar correctly

- src/components/my-map/index.ts
- src/components/my-map/utils.ts
When drawing or selecting features, dispatch their associated geojson change events in two projections: EPSG:3857 (web mercator) & EPSG:27700 (BNG). Previously, we defaulted to only EPSG:3857. 
In PlanX, this will enable us to easily get both the Easting (X), Northing (Y) & longitude, latitude coordinates of a point or polygon without needing to install any extra dependencies to handle further conversions later. 
Will flag as a **break** in our next release, as it changes the data format output by the event!
> feat: dispatch geojsonChange events in two projections

- index.html
- src/components/my-map/utils.ts
fixes bug spotted over here: https://github.com/theopensystemslab/planx-new/pull/1377#discussion_r1091647359
geojson change events now logging out "EPSG:27700" coordinates as proper 6-digit positive integers, "EPSG:3857" coordinates were always correct - and remain so!
> fix: correctly set geojson writeFeaturesObject options for coordinates projected in EPSG:27700

- package.json
- pnpm-lock.yaml
- src/components/address-autocomplete/main.test.ts
`lastTwoCalls()` is not particularly elegant, but works!
This will close https://github.com/theopensystemslab/map/pull/264 and close https://github.com/theopensystemslab/map/pull/254
> chore: Bump versions for`@testing-library/dom` and `vitest`

- src/components/address-autocomplete/index.ts
Now properly displays full address titles for postcode ME7 1NH
> fix: split on last occurance of council name, not first, in address-autocomplete dropdown options

- src/components/address-autocomplete/index.ts
I missed this in #275, which only fixed the visual display, but failed to successfully dispatch an event on address selection because of mismatched formatting.
> fix: ensure autocomplete selected address formatting always matches option

- .github/dependabot.yml
- fixes YAML value for PNPM
- adds checks for github action updates too
- better aligns to planx-new configuration https://github.com/theopensystemslab/planx-new/pull/1868
we have a small number of dependencies over here so not limiting number of open PRs from dependabot at any given time.
> fix: better dependabot configuration

- index.html
- pnpm-lock.yaml
- src/components/my-map/index.ts
Introduces an optional prop `clipGeojsonData` that can be set to disable a user panning/navigating outside of their own council. 
I originally was trying to apply a clipping/mask layer but I think that requires more style tinkering than its worth in our case, and this simpler option of applying an extent to the viewport should satisfy what we need ! 
See these docs / examples to compare:
- https://openlayers.org/en/latest/examples/extent-constrained.html
- https://openlayers.org/en/latest/examples/layer-clipping-vector.html
Next steps:
- Review/merge this PR
- Queue up new map release https://github.com/theopensystemslab/map/pull/364
- Open a planx-new branch with the upgrade
- Set the `clipGeojsonData` based on the existing `teams.setting.boundary` geojson if it exists
- Switch off …
> feat: clip viewport based on geojson extent

- src/components/my-map/docs/my-map-draw.doc.js
- src/components/my-map/drawing.ts
- src/components/my-map/index.ts
- In [Bops](https://github.com/unboxed/bops), we want to be able to draw a polygon on the map to visualise a consultation area where we return the addresses in that drawn area. However, this is currently hardcoded in red and to distinguish between the red line boundary and consultation area we preferably want this in a different colour that can be customisable. This PR adds this ability.
- The drawingColor and drawingColorFill defaults to what we usually expect for the red line boundary
Trello ticket:
https://trello.com/c/IQsb3WNF/1908-improve-content-and-layout-for-querying-neighbour-addresses-by-polygon-search
> Allow drawing colour and fill to be customisable

- src/components/my-map/index.ts
- Default to geojsonColor if the properties color object does not exist
- Can be added to feature i.e. `"properties": {"color": "#e670fc"}`
https://trello.com/c/IQsb3WNF/1908-improve-content-and-layout-for-querying-neighbour-addresses-by-polygon-search
> Set color of polygon with color set in the geojson feature properties

- .github/dependabot.yml
- package.json
- pnpm-lock.yaml
- Only run monthly
- Ignore known breaking changes (OpenLayers and happy-dom - we can manually update these when we want to)
- Fix node types to v18.16.1
> chore: Update dependabot config

- src/components/my-map/drawing.ts
Addresses feedback raised around displaying Title boundaries from Land Registry here https://github.com/theopensystemslab/planx-new/pull/2561
> fix: display`drawGeojsonData` vertices in cases of MultiPolygons too

- src/components/my-map/index.ts
- src/components/my-map/os-layers.ts
- src/components/my-map/styles.scss
Previously, the map supported a single prop `osCopyright` to specify the basemap attibution. This was un-collapsed by default and not configurable.
Now, we'll support multiple copyright props and expose the collapse prop to the user. Multiple copyrights are styled to be stacked on top of each other, rather than single-line.
Before / still default state:
Now / maximum three distinct attributions:
Now / collapsed attributions:
> feat: ability to set multiple custom attributions and collapse

- src/components/my-map/index.ts
Creates a property showNeighbourMark which when switched on creates a marker for each point passed in on the geojsonData property.
This will be useful in BOPS as it can be difficult to know when drawing a polygon whether you have selected the neighbouring properties. BOPS will pass the coordinates of the neighbours via the geojsonData prop.
> feat: Show neighbouring properties as points on map

- index.html
- src/components/my-map/index.ts
- src/components/my-map/main.test.ts
- src/components/my-map/styles.scss
A number of styling tweaks based on feedback from Planx's most recent accessibility audit: 
Future scope / followup:
> fix: usability improvements

- src/components/my-map/index.ts
Introduces `aria-controls` to attribution collapse button, and corresponding `id` to attribution list.
> fix(a11y): Add aria-controls to attribution toggle and list

- src/components/my-map/index.ts
This PR is relate to the missing role in the div wrapping the map that was found on the process of addressing accessibility concerns on the DPR/Public Index
> add role to map

- index.html
- src/components/my-map/drawing.ts
Replaces #464 - let's introduce one new shape at a time ! 
**Changes:**
- `drawType` prop now supports `Circle` in addition to original `Polygon` (still default) and `Point`
- We anticipate using this in Planx to mark the location of trees
- Supports modifying the circle simply by grabbing any edge and dragging - there will _not_ be visible vertice cues like we have with polygon modify
- Refactors styling helper methods and swaps out all `drawType` ternaries to switch statements, which will scale a lot nicer as we support more draw types going forward (for now, the circle is sharing stroke and fill styles with the polygon)
**Followup PRs:**
- Dispatch geojson & area change events when `drawType="Circle"` 
- "Circle" is not a supported GeoJSON type, so we'll transform it to a polygon first …
> feat: add support for drawing and modifying `Circle` geometry types

- index.html
- src/components/my-map/drawing.ts
- src/components/my-map/index.ts
- src/components/my-map/os-features.ts
Our styling-related props haven't always been so consistent, so let's tidy them up with a v1 release in mind & flag some as deprecated. 
Here's a quick overview of exisitng & changing style-related props based on various modes/functionalities:
- **Drawing**
- `drawColor` (string) - fill automatically applied at 20% (used to be 10%)
- ~`drawPointColor` (string)~ now deprecated - it's only possible to set a single `drawType` at a time anyways, so `drawColor` is sufficient
- ~`drawFillColor` (string)~ now deprecated
- `drawPointer` (enum)
- **Showing a center map marker** (based on lat,lng props _not_ geojson)
- `markerColor` (string)
- `markerImage` (enum)
- **Displaying GeoJSON data**
- `geojsonColor` (string)
- `geojsonFill` (boolean) - 20% if true
- **Showing OS Features at point**
- …
> break: condense and deprecate redundant styling-related props

- src/components/my-map/index.ts
Quick one-line fix for a bug that was occuring when `basemap="MapboxSatellite"` & `drawMode` was enabled ! 
Now drawn features are shown _on top of_ the basemap when they're completed (`geojsonChange` events confirmed they were still there, just beneath the satellite imagery later)
> fix: set explicit z-index for drawing layer

- index.html
- src/components/my-map/index.ts
- src/components/my-map/utils.ts
Follows on from #466 
**Changes:**
- Similar to `drawMode` - the `clickFeatures` functionality dispatches geojson & area events which should stay consistent with recent changes we've made to event dispatching - so we're deprecating `featuresAreaChange` event and instead setting `"area"` directly on the `featuresGeojsonChange` event data "properties"
- Deprecates `areaUnit` prop and simply sets _both_ `"area.squareMetres"` and `"area.hectares"` anywhere we calculate the area (these field names & new number type are more consistent with ODP Schema too)
> fix: update `featuresGeojsonChange` event to match new `geojsonChange` behavior

- CHANGELOG.md
- package.json
Queuing up a pre-release !
After this merges, will run `npm publish --tag next` rather than typical `npm publish` per thread here: https://gist.github.com/schmich/d04acc4b02b45e489f329cfdf3280a3f?permalink_comment_id=4483624#gistcomment-4483624
> v1.0.0-alpha.0

- index.html
- src/components/my-map/index.ts
Caught while testing List & MapAndLabel in planx-new - follows on #480
> fix: ensure marker & geojson layers are on top of satellite basemap

- src/components/my-map/index.ts
Fixes bug described here: https://github.com/theopensystemslab/planx-new/pull/3568#discussion_r1732611723
Now displayed! :pushpin:
> fix: ensure point features passed in via `geojsonData` have associated style

- src/components/my-map/drawing.ts
> fix: increase `drawMany` label font size and default drawing point size

- CHANGELOG.md
- package.json
Another pre-release which we'll tag `@next` when publishing to NPM :next_track_button:
> v1.0.0-alpha.1

- src/components/my-map/index.ts
Previously, when a feature was modified it's label would shift because internally it was moving to the last position in the drawing source. Now, keep labels on modify by checking if the "label" property already exists and only add new labels to new features.
Expect we might revisit this again when getting further into remove-one-at-a-time, but this fixes our known existing bug !
> fix: maintain drawing labels when modifying features

- src/components/my-map/drawing.ts
Same functionality as `geojsonData` now ! 
If initial features are set to pre-populate the drawing layer, read the `color` property from `drawGeojsonData` if it's set, else default to the `drawColor` prop. Label text is already populated the same way.
Eg this map is produced by this sample data - I think this should enable us to highlight a specific feature based on the active tab in Map&Label 
```js
const map = document.querySelector("my-map");
map.drawGeojsonData = {
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
-0.12779689203071595,
51.507483251157424
],
[
-0.12782371412086485,
51.50738892768874
],
[
-0.1276533938484192,
51.50742148182832
],
[
-0.12770033250617982,
51.50751079691233
],
[
-0.12779689203071595, …
```
> feat: read color from `drawGeojsonData` properties if set

- index.html
- src/components/my-map/index.ts
Flagged while testing `drawMany` 
I honestly don't fully understand what was happening here, but my best guess is that is has to do with how OpenLayer's `change` event listens to more internal events than just adding features as we _see_ them on the map, therefore anything called in this block may be firing off more often than we expect? 
Setting the label based on the current length of all features, rather than an index of the one we're iterating over, seems to do the trick - labels are consistently incrementing by one now!
> fix: ensure `drawMany` feature labels are incremental

- src/components/my-map/index.ts
By default, the "Reset" control is responsible for two things: 
- Resetting the map viewport based on displayed data or center coordinate & zoom configs
- Clearing all data from the drawing source if `drawMode` is enabled
This adds a new prop `resetViewOnly` that allows us to still show a "Reset" control when in `drawMode`, but retain data when clicked and _only_ reset the map viewport. This is useful if you want a "Remove" button to live in another part of your UI - like we're doing in PlanX here https://github.com/theopensystemslab/planx-new/pull/3625
> feat: add `resetViewOnly` prop to retain data but reset map position

- src/components/my-map/controls.ts
Updates direction of reset icon (`↺`) to be consistent with global PlanX reset button.
> style: Reset icon direction reverse

- src/components/my-map/drawing.ts
Improves visibility of point labels by removing character stroke and keeping background/text colour constant (not dependent on custom colour selection).
**Preview (before vs after):**
> style: Improve legibility of dot labels

- src/components/my-map/drawing.ts
- src/components/my-map/index.ts
Quick follow-on to #507 
- Ensures drawing a _single_ point uses same style as `drawMany` with hidden labels
- Bumps radius of center marker & geojson data points to match drawing points
> fix: consistent point styles

- README.md
Jotting these steps down, mostly for myself, since we've been alternating between releases & pre-releases lately! 
Ultimately still one to script into a GitHub Action at some point, but not frequent or time consuming currently :+1:
> docs: add steps for deploying/releasing to NPM

- src/components/geocode-autocomplete/index.ts
- output 4326 coordinates
belatedly realizing we need to pass lat/lng to the next API here, so adding that to the output;
the BNG coordinates are still present in the output if those need to be used anywhere.
> fix: output 4326 for lookup against planning.data.gov.uk API

- src/components/my-map/index.ts
When rendering a static geojson `FeatureCollection` (eg output by `drawMode` + `drawMany`), we want the option to display feature labels! Labels will be "off" by default. Styles (label position, size, stroke & fill) match configs for the drawing vector layer.
Examples for various `drawType`:
> feat: add `showGeojsonDataLabels` prop
